import brand from '../assets/images/Rectangle 7.png'
const products = [
  {
    id: 1,
    image: brand,
    title: 'Angels malu zip jeans slim black used',
    category: 'TOP WOMEN',
    low_price: '235.01',
    discount_price: '35.01',
  },
  {
    id: 2,
    image: brand,
    title: 'Angels malu zip jeans slim black used',
    category: 'TOP WOMEN',
    low_price: '235.01',
    discount_price: '35.01',
  },
  {
    id: 3,
    image: brand,
    title: 'Angels malu zip jeans slim black used',
    category: 'TOP WOMEN',
    low_price: '235.99',
    discount_price: '35.99',
  },
  {
    id: 4,
    image: brand,
    title: 'Angels malu zip jeans slim black used',
    category: 'TOP Male',
    low_price: '235.01',
    discount_price: '35.01',
  },
  {
    id: 5,
    image: brand,
    title: 'Angels malu zip jeans slim black used',
    category: 'TOP WOMEN',
    low_price: '235.01',
    discount_price: '35.01',
  },
  {
    id: 6,
    image: brand,
    title: 'Angels malu zip jeans slim black used',
    category: 'TOP WOMEN',
    low_price: '235.01',
    discount_price: '35.01',
  },
  {
    id: 7,
    image: brand,
    title: 'Angels malu zip jeans slim black used',
    category: 'TOP Male',
    low_price: '235.01',
    discount_price: '35.01',
  },
  {
    id: 8,
    image: brand,
    title: 'Angels malu zip jeans slim black used',
    category: 'TOP WOMEN',
    low_price: '235.01',
    discount_price: '35.01',
  },
]
export default products
